services:
  redis-server:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - redis-server
  api:
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - redis-server
      - postgres
  client:
    build:
      context: ./client
    depends_on:
      - api
  nginx:
    build:
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - 8081:80
