apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: complex
build:
  local:
    push: false
  artifacts:
    - image: kodega2016/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .

    - image: kodega2016/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .

    - image: kodega2016/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
manifests:
  rawYaml:
    - k8s/client-deployment.yml
    - k8s/database-persistent-volume-claim.yml
    - k8s/ingress-service.yml
    - k8s/postgres-deployment.yml
    - k8s/redis-deployment.yml
    - k8s/server-deployment.yml
    - k8s/worker-deployment.yml
