name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for worker
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/multi-worker:latest

      - name: Build and push Docker image for server
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/multi-server:latest

      - name: Build and push Docker image for nginx
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/multi-nginx:latest

      - name: Build and push Docker image for client
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/multi-client:latest
